### ISSUE TITLE
预训练模型什么时候发布呢？

### ISSUE THREAD

**Issue by Lireanstar** [MatNLP/SMedBERT#1]
您好，你们的工作十分有意义，请问预训练模型何时发布呢？

**Comment by algoflow19** [comment]
你好，代码是已经准备好开源的，但是资源需要公司审核批准才能放，这样没有资源现在我们放出来代码也没法运行。

**Comment by algoflow19** [comment]
可以关注 #2 我们最近会放代码出来，但是公司资源审核流程太慢了，我们也很无奈。
