### ISSUE TITLE
预训练语言模型类型

### ISSUE THREAD

**Issue by Smile-L-up** [MatNLP/SMedBERT#4]
你好，readme里的模型下载链接是SMedBERT吗？但是链接显示是base，有点懵。可以贴个链接吗？非常感谢。

**Comment by algoflow19** [comment]
链接没错的，我没有改文件名字。
提醒一下，这个weight适配的是原来的知识图谱，如果你现在要用这个模型的话，最好用自己的图谱进行预训练来使用，这个weight可能目前派不上用场。。。
