### ISSUE TITLE
run_pretrain_stream无法运行

### ISSUE THREAD

**Issue by Green-li** [MatNLP/SMedBERT#6]
run_pretrain_stream.py第80行：
```
...
for key in entity_dict.keys():
    if (len(key) > 1 and not key.isdigit()):
        ww_tree.insert(key)
ebmedding.
...
```
这句`embedding.`报错，是少写了什么东西还是其他的原因？
应该直接删掉？还是需要补全一下代码？

另外：`from pytorch_pretrained_bert.modeling import BertForHyperPreTraining, ERNIEForPreTraining`
在`pytorch_pretrained_bert.modeling` 文件中并没有找到`ERNIEForPreTraining`这个模型。
请问是使用的是transformers里面的模型代码吗？

**Comment by algoflow19** [comment]
谢谢关注，应该是最近更新的时候发生的问题，我会再检查下。

**Comment by algoflow19** [comment]
我更新了文件，你可以再试试看

**Comment by algoflow19** [comment]
Duplicate of # #7
