### ISSUE TITLE
pageRank文件，ERNIEForPreTraining没有实现

### ISSUE THREAD

**Issue by zmcadlf** [MatNLP/SMedBERT#7]
请问一下，pageRank文件是要自己写吗？
还有/pytorch_pretrained_bert/modeling.py 里面的ERNIEForPreTraining这个功能好像没有实现？

**Comment by ztl-35** [comment]
你好，按照论文中Section 3.2和PageRank基本公式在自己的KG上写代码统计即可

**Comment by ztl-35** [comment]
> 请问一下，pageRank文件是要自己写吗？ 还有/pytorch_pretrained_bert/modeling.py 里面的ERNIEForPreTraining这个功能好像没有实现？

你好，按照论文中Section 3.2和PageRank基本公式在自己的KG上写代码统计即可

**Comment by zmcadlf** [comment]
那ERNIEForPreTraining这个也是自己写？这个train的时候好像要用到

**Comment by algoflow19** [comment]
谢谢关注，我会检查下，尽快搞好。

**Comment by algoflow19** [comment]
我更新了文件，你可以再试试看
